### ISSUE TITLE
ssrf.py doesn't work 

### ISSUE THREAD

**Issue by MR-pentestGuy** [m4ll0k/Bug-Bounty-Toolz#13]
Traceback (most recent call last):
  File "ssrf.py", line 37, in main
    request = requests.get(
  File "/home/sanath/.local/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/sanath/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/sanath/.local/lib/python3.8/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/home/sanath/.local/lib/python3.8/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/home/sanath/.local/lib/python3.8/site-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/home/sanath/.local/lib/python3.8/site-packages/requests/models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ssrf.py", line 58, in <module>
    main(url,sys.argv[2])
  File "ssrf.py", line 46, in main
    print('[ERROR] '+err)
TypeError: can only concatenate str (not "MissingSchema") to str

how i used it 
python3 ssrf.py urls.txt burpcolllab

**Comment by m4ll0k** [comment]
Hi,

Show me full command.

**Comment by MR-pentestGuy** [comment]
python3 ssrf.py urls.txt burpcolllab
hey i used endpoints instead of alivesubs 
looks like it doesn't work on endpoints
and also if the alivesubs are greater than 1000 it breaks up

**Comment by MR-pentestGuy** [comment]
looks like it doesn't work on endpoints

**Comment by MR-pentestGuy** [comment]
and also if the alivesubs are greater than 1000 it breaks up
